blank_issues_enabled: false
contact_links:
  - name: ğŸŒ Noughty Linux Website
    url: https://noughtylinux.org
    about: Visit our main website for updates, and more information about our projects
